FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["RO.DevTest.WebApi/RO.DevTest.WebApi.csproj", "RO.DevTest.WebApi/"]
COPY ["RO.DevTest.Application/RO.DevTest.Application.csproj", "RO.DevTest.Application/"]
COPY ["RO.DevTest.Domain/RO.DevTest.Domain.csproj", "RO.DevTest.Domain/"]
COPY ["RO.DevTest.Infrastructure/RO.DevTest.Infrastructure.csproj", "RO.DevTest.Infrastructure/"]
COPY ["RO.DevTest.Persistence/RO.DevTest.Persistence.csproj", "RO.DevTest.Persistence/"]
RUN dotnet restore "RO.DevTest.WebApi/RO.DevTest.WebApi.csproj"
COPY . .
WORKDIR "/src/RO.DevTest.WebApi"
RUN dotnet build "RO.DevTest.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RO.DevTest.WebApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RO.DevTest.WebApi.dll"]